'use client'
import { motion } from 'framer-motion'
import GlobeCanvas from './GlobeCanvas'

const ease: [number, number, number, number] = [0.23, 1, 0.32, 1]

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1, delayChildren: 0.05 } },
}
const item = {
  hidden: { opacity: 0, y: 24 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.6, ease } },
}

const EMAIL_SHOWN = `Dear Professor Rossi,

I came across your 2024 paper on post-infarct ventricular remodeling. Your findings on collagen cross-linking during scar maturation were genuinely compelling, particularly the correlation with long-term ejection fraction outcomes.

I'm Maya Patel, a junior at Northlake University majoring in Biomedical Sciences (3.8 GPA). I'm drawn to cardiac repair research and would love to discuss the possibility of joining your lab as a research assistant this summer. I'd be happy to share my CV or any relevant coursework at your convenience.

Best,
Maya Patel`

export default function Hero() {
  return (
    <section className="hero" id="main" aria-labelledby="hero-h1">
      <GlobeCanvas />
      <motion.div
        className="hero-inner"
        variants={stagger}
        initial="hidden"
        animate="show"
      >
        <motion.h1 id="hero-h1" className="hero-h1 hero-wordmark" variants={item}>
          <span className="wordmark-pitch">Pitch</span><span className="wordmark-lab">Lab</span>
        </motion.h1>

        <motion.p className="hero-sub" variants={item}>
          Tell us where you want to do research. PitchLab reads each professor's latest published work, writes a unique and specific email, and sends it from your Gmail in minutes.
        </motion.p>

        <motion.div variants={item}>
          <a href="#pricing" className="btn btn-accent btn-lg">
            Start your outreach →
          </a>
        </motion.div>
      </motion.div>

      <motion.div
        className="hero-preview-wrap"
        initial={{ opacity: 0, y: 48 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.75, ease, delay: 0.5 }}
        role="img"
        aria-label="Example of a personalized email generated by PitchLab"
      >
        <div className="email-card">
          <div className="email-chrome" aria-hidden="true">
            <div className="ec-dot" style={{ background: '#ff5f57' }}/>
            <div className="ec-dot" style={{ background: '#ffbd2e' }}/>
            <div className="ec-dot" style={{ background: '#28ca42' }}/>
            <span className="email-chrome-label">New Message — Gmail</span>
          </div>

          <div className="email-fields">
            <div className="email-field">
              <span className="ef-label">From</span>
              <span className="ef-val"><strong>maya.patel@northlake.edu</strong></span>
            </div>
            <div className="email-field">
              <span className="ef-label">To</span>
              <span className="ef-val"><strong>dr.elenarossi@westbridge.edu</strong></span>
            </div>
            <div className="email-field">
              <span className="ef-label">Subject</span>
              <span className="ef-val"><strong>Cardiac repair research inquiry, Maya Patel</strong></span>
            </div>
          </div>

          <div className="email-body">
            <p className="email-body-text">
              {EMAIL_SHOWN}
            </p>
          </div>
        </div>
      </motion.div>
    </section>
  )
}
