'use client'
import { motion } from 'framer-motion'
import { useEffect, useRef, useState } from 'react'
import GlobeCanvas from './GlobeCanvas'

const ease: [number, number, number, number] = [0.23, 1, 0.32, 1]

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1, delayChildren: 0.05 } },
}
const item = {
  hidden: { opacity: 0, y: 24 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.6, ease } },
}

const FULL_EMAIL = `Dear Professor Rossi,

I came across your 2024 paper on post-infarct ventricular remodeling. Your findings on collagen cross-linking during scar maturation were genuinely compelling, particularly the correlation with long-term ejection fraction outcomes.

I'm Maya Patel, a junior at Northlake University majoring in Biomedical Sciences (3.8 GPA). I'm drawn to cardiac repair research and would love to discuss the possibility of joining your lab as a research assistant this summer. I'd be happy to share my CV or any relevant coursework at your convenience.

Best,
Maya Patel`

function charDelay(i: number): number {
  const prev = FULL_EMAIL[i - 1] ?? ''
  if (prev === '.' || prev === '!' || prev === '?') return 260 + Math.random() * 300
  if (prev === ',') return 70 + Math.random() * 90
  if (prev === '\n') return 180 + Math.random() * 260
  if (Math.random() < 0.03) return 180 + Math.random() * 320
  return 22 + Math.random() * 52
}

function EmailTyper() {
  const [displayed, setDisplayed] = useState('')
  const [done, setDone] = useState(false)
  const indexRef = useRef(0)
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  useEffect(() => {
    const start = setTimeout(() => {
      function type() {
        const i = indexRef.current
        if (i >= FULL_EMAIL.length) { setDone(true); return }
        setDisplayed(FULL_EMAIL.slice(0, i + 1))
        indexRef.current = i + 1
        timerRef.current = setTimeout(type, charDelay(i + 1))
      }
      type()
    }, 950)

    return () => {
      clearTimeout(start)
      if (timerRef.current) clearTimeout(timerRef.current)
    }
  }, [])

  return (
    <div style={{ position: 'relative' }}>
      {/* Ghost text holds the fixed height — invisible but in layout */}
      <p className="email-body-text" style={{ visibility: 'hidden', pointerEvents: 'none', userSelect: 'none' }} aria-hidden="true">
        {FULL_EMAIL}
      </p>
      {/* Typed text overlaid on top */}
      <p className="email-body-text" style={{ position: 'absolute', inset: 0, overflow: 'hidden' }}>
        {displayed}
        {!done && <span className="email-cursor" aria-hidden="true" />}
      </p>
    </div>
  )
}

export default function Hero() {
  return (
    <section className="hero" id="main" aria-labelledby="hero-h1">
      <GlobeCanvas />
      <motion.div
        className="hero-inner"
        variants={stagger}
        initial="hidden"
        animate="show"
      >
        <motion.h1 id="hero-h1" className="hero-h1 hero-wordmark" variants={item}>
          <span className="wordmark-pitch">Pitch</span><span className="wordmark-lab">Lab</span>
        </motion.h1>

        <motion.p className="hero-sub" variants={item}>
          Tell us where you want to do research. PitchLab reads each professor's latest published work, writes a unique and specific email, and sends it from your Gmail in minutes.
        </motion.p>

        <motion.div variants={item}>
          <a href="#pricing" className="btn btn-accent btn-lg">
            Start your outreach →
          </a>
        </motion.div>
      </motion.div>

      <motion.div
        className="hero-preview-wrap"
        initial={{ opacity: 0, y: 48 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.75, ease, delay: 0.5 }}
        role="img"
        aria-label="Example of a personalized email generated by PitchLab"
      >
        <div className="email-card">
          <div className="email-chrome" aria-hidden="true">
            <div className="ec-dot" style={{ background: '#ff5f57' }}/>
            <div className="ec-dot" style={{ background: '#ffbd2e' }}/>
            <div className="ec-dot" style={{ background: '#28ca42' }}/>
            <span className="email-chrome-label">New Message — Gmail</span>
          </div>

          <div className="email-fields">
            <div className="email-field">
              <span className="ef-label">From</span>
              <span className="ef-val"><strong>maya.patel@northlake.edu</strong></span>
            </div>
            <div className="email-field">
              <span className="ef-label">To</span>
              <span className="ef-val"><strong>dr.elenarossi@westbridge.edu</strong></span>
            </div>
            <div className="email-field">
              <span className="ef-label">Subject</span>
              <span className="ef-val"><strong>Cardiac Repair Research Inquiry - Maya Patel</strong></span>
            </div>
          </div>

          <div className="email-body">
            <EmailTyper />
          </div>
        </div>
      </motion.div>
    </section>
  )
}
